cabal-version:      2.2
name:               todo-exercise
version:            0.1.0.0
synopsis:           TDD exercise - Todo list manager
build-type:         Simple

library
  exposed-modules:  Todo
  hs-source-dirs:   src
  build-depends:    base >= 4.14 && < 5
  default-language: Haskell2010
  ghc-options:      -Wall

test-suite todo-test
  type:             exitcode-stdio-1.0
  hs-source-dirs:   test
  main-is:          Spec.hs
  build-depends:
      base             >= 4.14 && < 5
    , todo-exercise
    , tasty
    , tasty-hunit
    , tasty-quickcheck
    , QuickCheck
  default-language: Haskell2010
  ghc-options:      -Wall
