name:                 todo-exercise
version:              0.1.0.0
visibility:           public
id:                   todo-exercise-0.1.0.0-inplace
key:                  todo-exercise-0.1.0.0-inplace
synopsis:             TDD exercise - Todo list manager
abi:                  inplace
exposed:              True
exposed-modules:      Todo
import-dirs:
    /home/progressio/ost/git/todo-exercise/dist-newstyle/build/x86_64-linux/ghc-9.6.7/todo-exercise-0.1.0.0/build

library-dirs:
    /home/progressio/ost/git/todo-exercise/dist-newstyle/build/x86_64-linux/ghc-9.6.7/todo-exercise-0.1.0.0/build

library-dirs-static:
    /home/progressio/ost/git/todo-exercise/dist-newstyle/build/x86_64-linux/ghc-9.6.7/todo-exercise-0.1.0.0/build

dynamic-library-dirs:
    /home/progressio/ost/git/todo-exercise/dist-newstyle/build/x86_64-linux/ghc-9.6.7/todo-exercise-0.1.0.0/build

data-dir:             /home/progressio/ost/git/todo-exercise/.
hs-libraries:         HStodo-exercise-0.1.0.0-inplace
depends:              base-4.18.3.0
haddock-interfaces:
    /home/progressio/ost/git/todo-exercise/dist-newstyle/build/x86_64-linux/ghc-9.6.7/todo-exercise-0.1.0.0/doc/html/todo-exercise/todo-exercise.haddock

haddock-html:
    /home/progressio/ost/git/todo-exercise/dist-newstyle/build/x86_64-linux/ghc-9.6.7/todo-exercise-0.1.0.0/doc/html/todo-exercise
